# Generated by Django 4.2.15 on 2024-09-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0003_alter_detallefactura_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2,default=0.00, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
    ]
