# Generated by Django 4.2.16 on 2024-09-26 14:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0007_rename_observaciones_movimientostock_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
