# Generated by Django 4.2.16 on 2024-10-04 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0011_detalleventa_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
