# Generated by Django 4.2.16 on 2024-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0013_producto_imagen_alter_detallepedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default.png', null=True, upload_to='productos/'),
        ),
    ]
